services:
  storage:
    build:
      context: .     # path to storage Dockerfile
    container_name: storage_service
    env_file:
      - .env
    networks:
      - stockpulse-net
    restart: unless-stopped
  
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: stockpulse_user
      POSTGRES_PASSWORD: abcd1234
      POSTGRES_DB: stockpulse
    ports:
      - "5432:5432"
    networks:
      - stockpulse-net
    volumes:
      - stockpulse-data:/var/lib/postgresql/data

networks:
  stockpulse-net:
    external: true

volumes:
  stockpulse-data:
    driver: local